### ISSUE TITLE
1608 or 0603 ?

### ISSUE THREAD

**Issue by KjellMorgenstern** [kameleon-project/kameleon-board#8]
In the kameleon-core.brd file, resistors (and caps and leds) are of package "1608" but the scaled with 0.4064, so they actually appear as 0603 resistors:

```
<element name="R11" library="Kameleon" package="1608" value="NC" x="6.35" y="31.27375" smashed="yes">
<attribute name="NAME" x="6.35" y="31.27375" size="0.4064" layer="25" rot="R90" align="center"/>
</element>
```

Is intended for some reason?
I am not sure if this poses a problem when ordering parts.

**Comment by communix** [comment]
![image](https://user-images.githubusercontent.com/44126592/71561633-d8f43780-2a2d-11ea-9311-b2028ff7abda.png)

That's the "Metric code 1608" and It's the same as "Imperial code 0603" Please see the actual size in the picture.
